<a href="https://colab.research.google.com/github/CharlesPrado23/Bootcamp_TurmaNoite/blob/main/Conteudo_02/Exerc%C3%ADcios_de_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [7]:
### Questão 1
### Use o método np.unique para retornar um array sem duplicatas
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [ ]:
### Questão 2
### crie uma matriz (4,3) usando o método np.random.randn(x,y)

In [14]:
arr_ = np.random.randn(4,3)
arr_

array([[-0.47093531,  0.25704372, -0.47339335],
       [-0.5341303 ,  0.50958561, -0.10245965],
       [-0.0066098 , -0.00850996,  0.27614369],
       [-1.73026714,  1.78777898,  0.79717159]])

In [ ]:
### Questão 3 
### Retorne os elementos entre as linhas 2 e 3 ; e entre as colunas 1 e 2 
### Use o conceito de slice e armazene o resultada em outro array

In [27]:
array_slice = arr_[1:3, :2]

In [ ]:
### Questão 4 
### Calcule o valor médio da matriz da Questão 2 
### Calcule o valor médio da matriz da Questão 2 na direção horizontal
### Calcule o valor médio da matriz da Questão 2 na direção vertical

In [30]:
arr_.mean()

0.025118174795598535

In [31]:
arr_.mean(axis=1)

array([-0.22909498, -0.04233478,  0.08700798,  0.28489448])

In [32]:
arr_.mean(axis=0)

array([-0.68548564,  0.63647459,  0.12436557])

In [ ]:
### Questão 5
### usando o método arange , crie um array com 50 posições
### Modifique todos os valores para o valor igual a 1 
### Usando o método reshape crie uma matriz (10,50)

In [57]:
arr_q5 = np.arange(50)

In [55]:
arr_q5[0:] = 1

In [64]:
arr_q5.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])